1. Scalars: A *scalar* is just a number.
2. Vectors: A *vector* is a 1-D array. Mathmatically, vectors are usually assumed to be *column vector*
3. Matrices: A *matrix* is 2-D array of numbers.
4. Tensors: A mathematical object with more than two dimensions is colloquially referred to as a *tensor*. The number of dimensions a tensor has defines its *order*.



In [2]:
import numpy as np

In [3]:
## Any tensor of less than order n can be represented as an order-n tensor by supplying the missing dimensions of length 1.
t = np.array(42).reshape((1, 1, 1, 1, 1))
print(t)
print(t.shape)

# Or use newaxis,
t = np.array([[1, 2, 3], [4, 5, 6]])
print(t)
w = t[np.newaxis, :, :, np.newaxis]
print(w.shape)
print(w)

[[[[[42]]]]]
(1, 1, 1, 1, 1)
[[1 2 3]
 [4 5 6]]
(1, 2, 3, 1)
[[[[1]
   [2]
   [3]]

  [[4]
   [5]
   [6]]]]


In [8]:
## Array Operations

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([10, 100, 1000])
d = np.array([10, 11])

print(a + b)
print(a - b)
# Element-wise multiplication is often known as the Hadamard product
# Numpy extends the idea of element-wise operations into what it calls broadcasting
print(a * b)
print(a / b)

# Broadcasting
print(a + c)
print(c * a)
print(a / c)

e = d.reshape((2, 1))
print(e)
print(a+e)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[  11  102 1003]
 [  14  105 1006]]
[[  10  200 3000]
 [  40  500 6000]]
[[0.1   0.02  0.003]
 [0.4   0.05  0.006]]
[[10]
 [11]]
[[11 12 13]
 [15 16 17]]


## Vector Operations
Magnitude: ||X|| = sqrt(x0 x x1 + x1 x x2, ... xn x xn)
unit vector: v/||v||

In [7]:
v = np.array((2, -3, 4))
u = v / np.sqrt((v ** 2).sum())
print(u)

print(v)

# Inner product (dot product)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))
print((a * b).sum())

# Cosine 
cosangle = np.dot(a, b) / np.sqrt(np.dot(a, a) * np.dot(b, b))
print(cosangle)
# angle = arccos(cosangle)
print(np.arccos(cosangle) * 180 / np.pi)

# Project a to b 
print(np.dot(a, b) / np.dot(b, b) * b)

# Outer product
print(np.outer(a, b))


[ 0.37139068 -0.55708601  0.74278135]
[ 2 -3  4]
32
32
0.9746318461970762
12.933154491899135
[1.66233766 2.07792208 2.49350649]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[ 4 10 18]


## The CARTESIAN PRODUCT

The *Cartesian product* is a new set, each element of which is one of the possible pairings of elements from A and B. 

![Cartesian Product](chapter5/cartesian-product.png)

## Cross Product 
This operator is only defined for 3D space. The cross product of *a* and *b* is a new vector that is perpendicular to the plane containing *a* and *b*. Note, this does not imply that *a* and *b* are themselves perpendicular. 

![Cross Product](chapter5/cross-product.png)

In [8]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
print(np.cross(a, b))
c = np.array([1, 1, 0])
print(np.cross(a, c))

[0 0 1]
[0 0 1]


## Matrix Multiplication 

*(AB)C* = *A(BC)*

*A(B + C)* = *AB* + *AC*

*(A+B)C* = *AC* + *BC*

*AB* <> *BA*

### Kronecker Product
![Kronecker Product](chapter5/kronecker-product.png) 

In [11]:
a1 = np.array([1, 2, 3])
ar = np.array([[1, 2, 3]])
ac = np.array([[1], [2], [3]])
b1 = np.array([1, 2, 3])
br = np.array([[1, 2, 3]])
bc = np.array([[1], [2], [3]])
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

def dot(a, b):
    try:
        return np.dot(a, b)
    except:
        return "fails"

print(dot(a1, b1))
print(dot(a1, br))
print(dot(a1, bc))
print(dot(ar, b1))
print(dot(ar, br))
print(dot(ar, bc))
print(dot(ac, b1))
print(dot(ac, br))
print(dot(ac, bc))
print(dot(A, a1))
print(dot(A, ar))
print(dot(A, ac))
print(dot(a1, A))
print(dot(ar, A))
print(dot(ac, A))
print(dot(A, B))

# Kronecker product
print(np.kron(A, B))

14
fails
[14]
[14]
fails
[[14]]
fails
[[1 2 3]
 [2 4 6]
 [3 6 9]]
fails
[14 32 50]
fails
[[14]
 [32]
 [50]]
[30 36 42]
[[30 36 42]]
fails
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[ 9  8  7 18 16 14 27 24 21]
 [ 6  5  4 12 10  8 18 15 12]
 [ 3  2  1  6  4  2  9  6  3]
 [36 32 28 45 40 35 54 48 42]
 [24 20 16 30 25 20 36 30 24]
 [12  8  4 15 10  5 18 12  6]
 [63 56 49 72 64 56 81 72 63]
 [42 35 28 48 40 32 54 45 36]
 [21 14  7 24 16  8 27 18  9]]
